language: python
cache: pip
services:
  - docker
env:
  CONTAINER: aquarius-web
before_install:
  - cp aquarius/config.py.example aquarius/config.py
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose up -d
install:
  - ./wait-for-it.sh web:8000 -- docker-compose exec $CONTAINER pip install coverage pre-commit
  - docker-compose exec $CONTAINER pre-commit install
script:
  - docker-compose exec $CONTAINER pre-commit run --all-files --show-diff-on-failure
  - docker-compose exec $CONTAINER coverage run manage.py test
after_script:
  - docker-compose exec $CONTAINER coverage report -m
notifications:
  email: false
