version: '3'

services:
  aquarius-db:
    image: postgres:10.4
    volumes:
      - aquariusdb:/var/lib/postgresql/data/
  aquarius-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - aquarius-db

volumes:
  aquariusdb:
