version: '3'

services:
  aquarius_db:
    image: postgres:10.4
  aquarius_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - aquarius_db
