version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
  web:
    build: .
    environment:
      - TRAVIS=${TRAVIS} # This imports the TRAVIS environment variable into the container so we can use it for testing, ex: if os.getenv('TRAVIS') == 'true'.
    # entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
