version: '3'

services:
  aquarius-db:
    image: postgres:10.4
    volumes:
      - aquariusdb:/var/lib/postgresql/data/
  aquarius-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8002}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8002}:${APPLICATION_PORT:-8002}"
    depends_on:
      - aquarius-db

volumes:
  aquariusdb:
