# Generated by Django 3.2.5 on 2021-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0012_auto_20210818_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='archivesspace_resource',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
