# Generated by Django 3.2.5 on 2021-08-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transformer', '0013_package_archivesspace_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='ursa_major_accession',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
